### ISSUE TITLE
redirect loop with auth0

### ISSUE THREAD

**Issue by jcristau** [mozilla/nucleus#39]
Occasionally when visiting nucleus.m.o firefox will error out saying "this site is not redirecting properly".  Clearing cookies for the site fixes it.  I'll try to gather more info next time this happens to me; it might be related to an expired cookie?

**Comment by sylvestre** [comment]
@pmac rings a bell?

**Comment by pmac** [comment]
Yeah. It's the same as https://github.com/mozilla/airmozilla/issues/827 I'm pretty sure. tl;dr is that it's an issue in our OIDC library we use to connect with auth0, and hopefully will be fixed soon and we can update. Apologies for the problems. The fix for now is to clear nucleus cookies when it happens.

**Comment by pmac** [comment]
The fix for this has been released in the `mozilla-django-oidc` lib. I'll be upgrading that, which should fix this, as part of #40. I'll leave this open until we verify it's fixed, but watch that issue if you'd like to know when it should be done.

**Comment by pmac** [comment]
It turns out #40 is a bit more complex than I thought and isn't likely to be done very soon. So I've gone ahead with an upgrade of a bunch of libraries in 2385659ecfaaa6fa4ec726884890d7d8c7b7599b which should also fix this. Please reopen if it happens again. This is deploying to production now.
