### ISSUE TITLE
Add a rollout indicator for release notes with a feature rollout

### ISSUE THREAD

**Issue by DonalMe** [mozilla/nucleus#810]
There is an increasing amount of requests for release notes about features shipped with a progressive rollout.
Currently, in this scenario, we start the release note with wording such as "Gradually rolling out in Fx119..."
To help users understand why they may not see a new feature even when they have updated to the latest release version,
This wording becomes repetitive as there can be multiple feature rollouts in the same release. 

As a Release Manager, I would like to set a flag in Nucleus that a release note is for gradual rollout, so that an indicator is displayed on the mozilla.org release notes page beside the note.

**Comment by DonalMe** [comment]
Note for when this hs been triaged.
Hopefully, UX working on mozilla.org could provide some direction here.

**Comment by stevejalim** [comment]
Chatting with Donal about this, it sounds like something as lightweight as an icon with a tooltip beside the relevant note  will be enough

I suppose in theory it's possible we might end up with a release featuring a lot of 'progressive rollout' features, and so a lot of things with icons beside them, but I think the likelihood of that is relatively low.

**Comment by stevejalim** [comment]
<img width="1628" alt="Screenshot 2023-10-30 at 17 32 34" src="https://github.com/mozilla/nucleus/assets/101457/737e7e37-775d-4356-a776-d8f2929b221e">


As a super-lo-fi mockup based on the [119 release notes page](https://www.mozilla.org/en-US/firefox/119.0/releasenotes/), I'm thinking something like this would work, either with word-based marker, or an icon.

@ehot - I'll happily defer to you about how you think this should look IRL. For a given FF release, there are multiple individual notes and this new icon could go beside any individual note.

I guess we'll also have to make something work that is fine if there is a large image in the release note, too

**Comment by ehot** [comment]
Hey yall. 
<img width="476" alt="do this" src="https://github.com/mozilla/nucleus/assets/2040610/8142a817-85be-4f01-9d2f-e10d61ae39ce">
Let's do the above solution:
- Main text to use: @include text-body-md;
- Helper text to use: @include text-body-sm or -xs (whatever looks good)
- Link the helper text to documentation we have explaining what a progressive rollout is. Perhaps we have something on MDN? I'm not sure that it's a term that an average person would know.
- The box around the disclaimer should be the same stroke and color as the dividers. If we have a variable for standard border radius, let's use that. If not, 8px border radius.
- SVG + PNG of the plants will be attached to this comment
- On small width screens, it can go 100% width, but it may look better at like 80% width so it doesn't look like a new section, but a part of its section.


<img width="632" alt="other placement options" src="https://github.com/mozilla/nucleus/assets/2040610/2923afe9-aaa8-4452-bbdf-f08272e957bc">
I also looked at a few other placement options. Because "* New" is not using a large font size, we want to use a smaller, yet still legible, one for this disclaimer. Also, This disclaimer is not as important as the release note itself, so I don't think it should be placed on the far left (a prominent spot for users who read form let to right), or as a section heading, as it makes the page potentially much longer. I like in a little box on the left as it conveys the info, but it's out of the way. 
![progressive](https://git
![progressive](https://github.com/mozilla/nucleus/assets/2040610/70fe2247-9813-48fb-a312-961d78685b1a)
hub.com/mozilla/nucleus/assets/2040610/17b57ff7-15de-4167-81bd-68c23ca6ed16)

**Comment by ehot** [comment]
[progressive.zip](https://github.com/mozilla/nucleus/files/13255440/progressive.zip)
^ The svg and png for the plants.

**Comment by stevejalim** [comment]
There's no definition of a progressive rollout in MDN, but maybe we can add an explanation as a tooltip to the "What is a progressive rollout?" line. 

Something like the following might work - @DonalMe please do suggest better/correct wording 😄 

> Certain new Firefox features are released gradually. This means some users will see the feature before everyone does. This approach helps us to get early feedback and lets us catch bugs and improve behaviour quickly, meaning more Firefox users overall have a better experience.

How's that sound?
