### ISSUE TITLE
Add a method to restrict a release notes to a geo-location

### ISSUE THREAD

**Issue by DonalMe** [mozilla/nucleus#811]
Release Management has received requests for release notes about features shipped with a progressive rollout to a specific country.

As a Release Manager, I would like to indicate in Nucleus that a release note is for a specific location, so only users browsing the  mozilla.org release notes page from that location will see the note.

**Comment by stevejalim** [comment]
@DonalMe Thanks for raising this. Some clarifiation questions for you:

1. Do you/we have a fixed lists of locations that should be picked from, please?

2. Are we likely to have multiple locations associated with a note?

Also, in the broader context, while it looks like we have locale support based on the URL of a release note  - e.g. https://www.mozilla.org/en-US/firefox/119.0/releasenotes/ has en-US in the URL, I don't believe there is any actual locale-specific logic currently available. As a faster, and potentially less complex route to a solution, what do you think about listing the locales a feature is available in, after teh release note? This would have the upside of avoiding confusion of different users in different locales seeing different release notes without a clear explanation why.

eg something like:

<img width="547" alt="Screenshot 2023-11-01 at 13 18 42" src="https://github.com/mozilla/nucleus/assets/101457/6bdf19ec-40e7-48f9-be31-7506f6034505">

**Comment by DonalMe** [comment]
@pascalchevrel could you comment on question 1?
- I'm assuming it should be the same list of locales as supported on mozilla.org

Re: Question 2
- The current ask is one location associated with a note. Although if it's not additional effort, it might be useful in the future to support multiple locations.

> As a faster, and potentially less complex route to a solution, what do you think about listing the locales a feature is available in, after teh release note?
I'll share this suggestion with the rest of the relman team for input

**Comment by pascalchevrel** [comment]
Locales and locations are 

> @pascalchevrel could you comment on question 1?
> 
>     * I'm assuming it should be the same list of locales as supported on mozilla.org

Locales and locations are different things, our locale codes indicate a language and optionally a language variant as spoken in a geography. Sometimes a locale code closely matches a geography (it for Italian => Italy), but locale codes such as de or fr are spoken in multiple countries. Is there a reason to restrict the number of countries to a short list and not include all countries? The requests we have for geoIP are usually related to the rolling out of a feature that is country specific due to legal reasons but we don't know yet what these countries are. I was thinking we would use all the ISO 3166-1 countries https://datahub.io/core/country-list

**Comment by stevejalim** [comment]
Given the local vs location distinction, I think it makes more sense to simply have an additional field where we can specify locations where a release is available. This could be free-form text, or a selection of countries from a multi-select in Nucleus. 

> The requests we have for geoIP are usually related to the rolling out of a feature that is country specific due to legal reasons but we don't know yet what these countries are

@pascalchevrel Do you mean that at the time release notes are written the relevant locations are not known, or are you speaking specifically about a current/WIP release note, please?

**Comment by stevejalim** [comment]
@DonalMe Just giving my suggestion above a bump:

> Given the locale vs location distinction, I think it makes more sense to simply have an additional field where we can specify locations where a release is available. This could be free-form text, or a selection of countries from a multi-select in Nucleus.

What do you think?

**Comment by DonalMe** [comment]
Thanks @stevejalim sorry, I missed this.
What would be the resulting behavior when the selection is specified?
Would only users browsing from that location see the note?

**Comment by stevejalim** [comment]
When the country selection is specified, it would show a list of the selected countries that the note applies to (below the note itself most likely).

As mentioned above, there's currently no geo-ip or locale-specific logic in play with release notes at the moment. Adding it is possible, of course, but it's a reasonable amount of work and geo-ip lookups are never 100% guaranteed to be accurate, so I'm thinking around this before diving in. 

The idea of simply listing the countries where a note is available also avoids confusion with different users in different locales seeing different release notes without a clear explanation why. (ie, being explicit about where Note X applies to is maybe better than hiding it away)

Does that seem a useful approach?

**Comment by stevejalim** [comment]
Actually - and contradicting myself quite a bit - the geo side isn't a big lift after all - most of the mechanism is around, just need surfacing, and there are a couple of ways we could do it. (Hat tip to @pmac for pointing this out.)

So yeah, I think we have three options that are worth sense-checking with the relman team:

Option 1) We can give you exactly what you ask for in your original request:

> only users browsing the mozilla.org release notes page from that location will see the note.

We'd set it up so that you select from a set of countries for the note with the same kind of widget you use to select which Release a Note belongs to. On www.mozilla.org, we'd either not render the note if the geo isn't appropriate, or we'd hide it with JS (TBC, but the result would be effectively the same)

Option 2) We don't hide information, we just add a line to make it clear which countries a Note is applies to via a text cue (similar to the screenshot posted earlier in the thread, but with country codes, not locale codes)

This reduces user confusion and surprise (eg edge cases where a US user is in Europe, for instance) and also generally shows what's happening with Firefox -- most people who read the relnotes are likely interested in the broader picture too, I'm guessing/assuming.

Option 3) We do nothing and the relman team just mentions the countries in the text of a Note, as you say 😄 

Let me know which way you'd prefer to go on this.

Sorry for the run around the houses here 😆

**Comment by DonalMe** [comment]
Discussed this with the relman team, Option 2 would be preferable.

**Comment by stevejalim** [comment]
@DonalMe no rush to reply, but I didn't clarify with you how many countries a note might be associated with: are we talking in single digits or more like several dozen countries, or sometihng in between? 


My assumption from the original description was that, because country-specific rollout is part of a progressive rollout, it would be to a small number of countries mentioned, then all countries. Was I off-the-mark there?

**Comment by DonalMe** [comment]
@stevejalim sorry for the delay

> are we talking in single digit
 
Correct - it would be single-digit countries, if not just one at any give time
